### PR TITLE
Change import to use current file location.

### PR DESCRIPTION
**Pull request by elinw**
It works now, but this will avoid potential future problems.

### CODE REVIEW

**Comment by colemanw** [comment]
Sorry I'm not too familiar with Joomla APIs but can you confirm this is backward compatible with Joomla 2.5 (which we still support)?

**Comment by elinw** [comment]
Oh good question, will check.

**Comment by elinw** [comment]
Yup good call. Leave as is to support both for now but maybe there should be a comment saying to change it when 2.5 support is dropped?

**Comment by colemanw** [comment]
Sure, want to update your PR to just adding a comment?

**Comment by elinw** [comment]
will send a new PR

**Pull request closed without merging**
